global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'nestjs-backend'
    static_configs:
      # 'backend' is the service name from your docker-compose file
      - targets: ['backend:3000']
